spring:
  application:
    name: Config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chaithra-Shenoy/ConfigurationProperty.git
          force-pull: true
      profile: development
  profiles:
    active:
    - development
 
server:
  port: 8999
